name: gpcs_hostel_portal
description: Hostel Management System for GP Chhatrapati Sambhajinagar.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  marquee: ^2.2.3
  intl: ^0.19.0
  # ADDED GEOLOCATOR FOR GPS ACCESS
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/gpcslogo.png
    - assets/images/logo.png